# Generated by Django 4.2.4 on 2023-08-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PO', 'PO'), ('IA', 'IA'), ('MCDA', 'MCDA')], max_length=5)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('locale', models.CharField(max_length=10)),
                ('title', models.TextField()),
            ],
        ),
    ]
