# Generated by Django 4.2.4 on 2023-08-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_blogpost_speaker_alter_blogpost_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('PO', 'PO'), ('IA', 'IA'), ('MCDA', 'MCDA'), ('DS', 'DS'), ('SIMU', 'SIMU')], max_length=5),
        ),
    ]
