# Generated by Django 4.2.4 on 2023-09-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='file',
            field=models.FileField(null=True, upload_to='mediafiles/pdfs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
