# Generated by Django 4.2.4 on 2023-09-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_file_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
