runtime: python310 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"


entrypoint: gunicorn -b :$PORT setup.wsgi

handlers:
- url: /images
  static_dir: static/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

